name: Github Action CI

on: 
  push:
    branches: [ master ]
    tags-ignore:
      - v0

jobs:
  testing:
    name: Unit Test
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: Install dependencies
      run: npm ci
    - name: Run unit test
      run: npm run test